/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Trabajador;
import Clases.ListaTrabajadores;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Manuel
 */
public class FrmActualizarTrabajador extends javax.swing.JFrame {
    private ListaTrabajadores lT;
    private Trabajador tra;

    public ListaTrabajadores getlT() {
        return lT;
    }

    public void setlT(ListaTrabajadores lT) {
        this.lT = lT;
    }

    public Trabajador getTra() {
        return tra;
    }

    public void setTra(Trabajador tra) {
        this.tra = tra;
    }
    /**
     * Creates new form FrmActualizarTrabajador
     */
    public FrmActualizarTrabajador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        tFNombresTrabajador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tFApePaTrabajador = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tFApeMaTrabajador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tFEdadTrabajador = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tFDireccionTrabajador = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tFDNITrabajador = new javax.swing.JTextField();
        jBActualizarTrabajador = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jBCerrar = new javax.swing.JButton();
        chkAdministrador = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tFNombresTrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(tFNombresTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 78, 179, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nombres");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 78, 152, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Apellido paterno");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 119, 152, 30));

        tFApePaTrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(tFApePaTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 119, 179, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Apellido materno");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 155, 152, 30));

        tFApeMaTrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(tFApeMaTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 156, 179, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Edad");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 197, 152, 30));

        tFEdadTrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(tFEdadTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 197, 179, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Direccion");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 238, 152, 30));

        tFDireccionTrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(tFDireccionTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 239, 179, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DNI");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 275, 152, 30));

        tFDNITrabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(tFDNITrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 276, 179, 30));

        jBActualizarTrabajador.setBackground(new java.awt.Color(0, 255, 51));
        jBActualizarTrabajador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBActualizarTrabajador.setText("ACTUALIZAR");
        jBActualizarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarTrabajadorActionPerformed(evt);
            }
        });
        jPanel7.add(jBActualizarTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 373, 179, 40));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("TRABAJADOR");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 163, 50));

        jBCerrar.setBackground(new java.awt.Color(0, 255, 51));
        jBCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBCerrar.setText("CERRAR");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel7.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 373, 191, 40));

        chkAdministrador.setText("Administrador");
        jPanel7.add(chkAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 313, 146, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     public void asignarValores(){
        tFNombresTrabajador.setText(this.tra.getNombre());
        tFApePaTrabajador.setText(this.tra.getApellidoPaterno());
        tFApeMaTrabajador.setText(this.tra.getApellidoMaterno());
        tFEdadTrabajador.setText(String.valueOf(this.tra.getEdad()));
        tFDireccionTrabajador.setText(this.tra.getDireccion());
        tFDNITrabajador.setText(this.tra.getDNI());
        if ( tra.isTipo() ){
            chkAdministrador.setSelected(true);
        }
        else{
            chkAdministrador.setSelected(false);
        }
    }

    private void jBActualizarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarTrabajadorActionPerformed
        if ( this.tFNombresTrabajador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta nombres","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ( this.tFApePaTrabajador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta apellido paterno","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ( this.tFApeMaTrabajador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta apellido materno","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ( this.tFEdadTrabajador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta edad","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ( this.tFDireccionTrabajador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta direccion","Error",JOptionPane.ERROR_MESSAGE);
        }
        if ( this.tFDNITrabajador.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta DNI","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        Trabajador newTra = new Trabajador(this.tra.getCodigo(),tFNombresTrabajador.getText(),tFApePaTrabajador.getText(),
            tFApeMaTrabajador.getText(),Integer.parseInt(tFEdadTrabajador.getText()),tFDireccionTrabajador.getText(),
            tFDNITrabajador.getText(),chkAdministrador.isSelected());
        this.lT.modificarDatos(newTra);
        this.lT.actualizarArchivo();
        JOptionPane.showMessageDialog(this, "REGISTRO EXITOSO","REGISTRO EXITOSO",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jBActualizarTrabajadorActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActualizarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAdministrador;
    private javax.swing.JButton jBActualizarTrabajador;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField tFApeMaTrabajador;
    private javax.swing.JTextField tFApePaTrabajador;
    private javax.swing.JTextField tFDNITrabajador;
    private javax.swing.JTextField tFDireccionTrabajador;
    private javax.swing.JTextField tFEdadTrabajador;
    private javax.swing.JTextField tFNombresTrabajador;
    // End of variables declaration//GEN-END:variables
}
