/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;
import Clases.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jose Manuel
 */
public class FrmActualizarProducto extends javax.swing.JFrame {
    private ListaProductos lP;
    private Producto pro;
    
    DefaultComboBoxModel modelo = new DefaultComboBoxModel();
    public Producto getPro() {
        return pro;
    }

    public void setPro(Producto pro) {
        this.pro = pro;
    }
    public ListaProductos getlP() {
        return lP;
    }

    public void setlP(ListaProductos lP) {
        this.lP = lP;
    }
    /**
     * Creates new form FrmActualizarProducto
     */
    public FrmActualizarProducto() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
    }
    
    public void llenarCategorias(String[] categoria){
        this.jCCategoriaProducto.removeAllItems();
        modelo = (DefaultComboBoxModel) this.jCCategoriaProducto.getModel();
        for ( int i = 0; i < categoria.length; i++){
            this.modelo.addElement(categoria[i]);
        }
        this.jCCategoriaProducto.setModel(modelo);
    }
    
    public void asignarValores(){
        tFNombreProducto.setText(pro.getNombre());
        tFPrecioProducto.setText(String.valueOf(pro.getPrecio()));
        switch ( pro.getCategoria() ){
            case "Lacteos" -> jCCategoriaProducto.setSelectedIndex(0);
            case "Carnes" -> jCCategoriaProducto.setSelectedIndex(1);
            case "Frutas y verduras" -> jCCategoriaProducto.setSelectedIndex(2);
            case "Pescados y mariscos" -> jCCategoriaProducto.setSelectedIndex(3);
            case "Limpieza" -> jCCategoriaProducto.setSelectedIndex(4);
            case "Panaderia y pasteleria" -> jCCategoriaProducto.setSelectedIndex(5);
            case "Dulces" -> jCCategoriaProducto.setSelectedIndex(6);
            case "Utiles escolares" -> jCCategoriaProducto.setSelectedIndex(7);
            case "Ropa" -> jCCategoriaProducto.setSelectedIndex(8);
        }
        tFMarcaProducto.setText(pro.getMarca());
        jSpStockProducto.setValue(pro.getStock());
        jdcFecha.setDate(pro.getFechaV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        tFNombreProducto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tFPrecioProducto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tFMarcaProducto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jBActualizarProducto = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jCCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jSpStockProducto = new javax.swing.JSpinner();
        jBCerrar = new javax.swing.JButton();
        jdcFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tFNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(tFNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 179, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nombre");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 139, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Precio");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 139, 30));

        tFPrecioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(tFPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 179, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Categoria");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 139, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Marca");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 139, 30));

        tFMarcaProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel10.add(tFMarcaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 179, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Stock");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 139, 30));

        jBActualizarProducto.setBackground(new java.awt.Color(0, 255, 1));
        jBActualizarProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBActualizarProducto.setText("ACTUALIZAR");
        jBActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarProductoActionPerformed(evt);
            }
        });
        jPanel10.add(jBActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 157, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ACTUALIZAR PRODUCTO");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 340, 50));

        jCCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lacteos", "Carnes", "Frutas y verduras", "Pescados y marisco", "Limpieza", "Panaderia y pasteleria", "Dulces", "Utiles escolares", "Ropa" }));
        jPanel10.add(jCCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 179, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Fecha de vencimiento");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 139, 30));

        jSpStockProducto.setModel(new javax.swing.SpinnerNumberModel());
        jPanel10.add(jSpStockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 179, 30));

        jBCerrar.setBackground(new java.awt.Color(0, 255, 1));
        jBCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBCerrar.setText("CERRAR");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel10.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 151, 40));

        jdcFecha.setDateFormatString("dd/MM/yyyy");
        jdcFecha.setName("jdc_Fecha"); // NOI18N
        jPanel10.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 179, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarProductoActionPerformed
        if ( tFNombreProducto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta nombres","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ( tFPrecioProducto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Falta precio del producto","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ( tFMarcaProducto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta marca del producto", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ( jSpStockProducto.getValue().equals(0)){
            JOptionPane.showMessageDialog(this, "Falta stock del producto", "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String categoria = jCCategoriaProducto.getItemAt(jCCategoriaProducto.getSelectedIndex());
        Producto newPro = new Producto(this.pro.getCodigo(),tFNombreProducto.getText(),
                Double.parseDouble(tFPrecioProducto.getText()),categoria,
                tFMarcaProducto.getText(),Integer.parseInt(jSpStockProducto.getValue().toString()),
                jdcFecha.getDate());
        this.lP.cambiarValores(newPro);
        JOptionPane.showMessageDialog(this, "SE HAN ACTUALIZADO LOS DATOS","REGISTRO EXITOSO",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jBActualizarProductoActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActualizarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarProducto;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JComboBox<String> jCCategoriaProducto;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JSpinner jSpStockProducto;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTextField tFMarcaProducto;
    private javax.swing.JTextField tFNombreProducto;
    private javax.swing.JTextField tFPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
