/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Clases.*;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.*;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.*;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author Jose Manuel
 */
public class FrmLogin extends javax.swing.JFrame {
    private SuperMercado supe;
    private int intentos;
    private List<String> completions;
    
    public SuperMercado getSupe() {
        return supe;
    }

    public void setSupe(SuperMercado supe) {
        this.supe = supe;
    }

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Color transparentColor = new Color(255, 255, 255, 200);
        this.jPanel3.setBackground(transparentColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tFUsuario = new javax.swing.JTextField();
        comboBoxUsuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        pFContrasenia = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        JBAceptar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        mostrarContraseniaClicked = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ocultarContraseniaClicked = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 11, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoLogin.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 39));

        tFUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tFUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tFUsuario.setToolTipText("");
        tFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFUsuarioKeyReleased(evt);
            }
        });
        jPanel3.add(tFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 280, 41));

        comboBoxUsuario.setEditable(true);
        jPanel3.add(comboBoxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 280, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONTRASEÑA");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 35));

        pFContrasenia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pFContrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(pFContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 280, 39));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INICIAR SESION");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 280, 34));

        JBAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBAceptar.setText("ACEPTAR");
        JBAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });
        jPanel3.add(JBAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 280, 44));

        jBCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBCerrar.setText("CERRAR");
        jBCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 280, 44));

        mostrarContraseniaClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrarContra.png"))); // NOI18N
        mostrarContraseniaClicked.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarContraseniaClicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarContraseniaClickedMouseClicked(evt);
            }
        });
        jPanel3.add(mostrarContraseniaClicked, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 368, 46, 46));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MOSTRAR CONTRASEÑA");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 216, 40));

        ocultarContraseniaClicked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ocultarContra.png"))); // NOI18N
        ocultarContraseniaClicked.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocultarContraseniaClicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarContraseniaClickedMouseClicked(evt);
            }
        });
        jPanel3.add(ocultarContraseniaClicked, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 368, 46, 46));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 340, 550));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blurred-background-supermarket-aisle-with-products_62890-121.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 580));

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 200, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   


    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        Sesion.getInstance().usuario = this.tFUsuario.getText();
        Sesion.getInstance().contrasenia = this.pFContrasenia.getText();
        Trabajador tra = supe.getlT().buscarUsuarioContrasenia(Sesion.getInstance().usuario, Sesion.getInstance().contrasenia);
        if (Sesion.getInstance().usuario.isEmpty() && Sesion.getInstance().contrasenia.isEmpty()){
            JOptionPane.showMessageDialog(this, "Campos vacios", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        else if ( intentos == 3 ){
            JOptionPane.showMessageDialog(this, "Se cerrara el programa", "",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        else{
            if ( tra == null ){
                JOptionPane.showMessageDialog(this, "No existe el trabajador\n Te quedan "+(3-intentos)+
                        " intentos","Error",JOptionPane.ERROR_MESSAGE);
                this.tFUsuario.setText("");
                this.pFContrasenia.setText("");
                this.tFUsuario.requestFocus();
                this.intentos++;
            }
            else{
                JOptionPane.showMessageDialog(this, "Bienvenido al sistema: "+tra.getNombre()+" "+tra.getApellidoPaterno(),"Mensaje de bienvenida",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                FrmVentanaPrincipal frVP = new FrmVentanaPrincipal(tra);
                frVP.setSup(this.supe);
                frVP.llenarComboBox();
                frVP.show();
            }
        }
       this.tFUsuario.setText("");
       this.pFContrasenia.setText("");
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        int confirmado = JOptionPane.showConfirmDialog(this, "¿Deseas salir?");
        if ( JOptionPane.OK_OPTION == confirmado ){
            System.exit(0);
        }
        else{
            return;
        }
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void mostrarContraseniaClickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarContraseniaClickedMouseClicked
        Color transparentColor = new Color(255, 255, 255, 200);
        this.jPanel3.setBackground(transparentColor);
        mostrarContraseniaClicked.setVisible(false);
        ocultarContraseniaClicked.setVisible(true);
        pFContrasenia.setEchoChar((char)0);
        pFContrasenia.setFont(new Font("Tahoma",Font.PLAIN,18));
    }//GEN-LAST:event_mostrarContraseniaClickedMouseClicked

    private void ocultarContraseniaClickedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarContraseniaClickedMouseClicked
        Color transparentColor = new Color(255, 255, 255, 200);
        this.jPanel3.setBackground(transparentColor);
        mostrarContraseniaClicked.setVisible(true);
        ocultarContraseniaClicked.setVisible(false);
        pFContrasenia.setEchoChar('\u2022');
        pFContrasenia.setFont(new Font("Tahoma",Font.BOLD,18));
    }//GEN-LAST:event_ocultarContraseniaClickedMouseClicked

    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //llenadoComboBoxUsuario();
        //llenadoListener();
        //sugerencias();
      
    }//GEN-LAST:event_formWindowActivated

    
    private void tFUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFUsuarioKeyReleased
        String userInput = tFUsuario.getText();

        SwingUtilities.invokeLater(() -> {
            NodoTrabajador nodo = supe.getlT().getCab();
            while (nodo != null) {
                if (userInput.equals(nodo.getTra().getUsuario())) {
                    String contrasenia = nodo.getTra().getContrasenia();
                    SwingUtilities.invokeLater(() -> pFContrasenia.setText(contrasenia));
                    break; // Detener el bucle después de encontrar una coincidencia
                }
                nodo = nodo.getSgte();
            }
            pFContrasenia.setText("");
        });
    }//GEN-LAST:event_tFUsuarioKeyReleased
   
    private List<String> getUsuariosCompletions() {
        List<String> completions = new ArrayList<>();
        NodoTrabajador aux = this.supe.getlT().getCab();
        while (aux != null) {
            completions.add(aux.getTra().getUsuario());
            aux = aux.getSgte();
        }
        return completions;
    }
    
    public void llenadoComboBoxUsuario(){
        comboBoxUsuario.removeAllItems();
        List<String> usuarios = getUsuariosCompletions();
        for ( int i = 0; i < usuarios.size(); i++ ){
            comboBoxUsuario.addItem(usuarios.get(i));
        }
    }   
    
    public void llenadoListener(){
        
        tFUsuario.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateComboBox();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateComboBox();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateComboBox();
            }
        });
        
    }
    
    private void updateComboBox() {
        String userInput = tFUsuario.getText();
        comboBoxUsuario.getEditor().setItem(userInput);
        completions = getUsuariosCompletions();
        comboBoxUsuario.removeAllItems();
        for (String user : completions ) {
            if (user.startsWith(userInput)) {
                comboBoxUsuario.addItem(user);
            }
        }
        if ( comboBoxUsuario.getItemCount() > 0 ){
            comboBoxUsuario.setPopupVisible(true);
        }
        else{
            comboBoxUsuario.setPopupVisible(false);
        }
        
        comboBoxUsuario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Object selectedItem = comboBoxUsuario.getSelectedItem();
                if (selectedItem != null) {
                   
                    tFUsuario.setText(selectedItem.toString());
                    
                }
            }
        });
        
     }
    
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SuperMercado sup = new SuperMercado();
                try {
                    sup.cargaPrincipalDatos();
                } catch (ParseException | IOException ex) {
                    Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                FrmLogin frLog = new FrmLogin();
                frLog.setSupe(sup);
                frLog.setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JComboBox<String> comboBoxUsuario;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mostrarContraseniaClicked;
    private javax.swing.JLabel ocultarContraseniaClicked;
    private javax.swing.JPasswordField pFContrasenia;
    private javax.swing.JTextField tFUsuario;
    // End of variables declaration//GEN-END:variables

    public void setLocationRelative(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
